version: "3.9"

services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php-fpm
    php-fpm:
        image: php:8-fpm
        container_name: php
        volumes:
            - ./src:/var/www/html